# Generated by Django 4.1.7 on 2023-03-22 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=200, unique=True)),
                ('status_type', models.CharField(choices=[('info', 'Information Only'), ('pending', 'Pending'), ('approved', 'Approved'), ('submitted', 'Submitted'), ('paid', 'Paid')], default='info', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='claim',
            name='owner',
        ),
    ]
