# Generated by Django 4.1.7 on 2023-03-22 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_status_remove_claim_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='id',
        ),
        migrations.AddField(
            model_name='claim',
            name='claim_number',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='claim',
            name='status',
            field=models.CharField(default='Information Only', max_length=50),
        ),
    ]
