# Generated by Django 4.1.7 on 2023-03-22 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_delete_status_remove_claim_id_claim_claim_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
