# Generated by Django 4.1.7 on 2023-03-25 00:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0004_claim_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='text',
        ),
        migrations.AddField(
            model_name='claim',
            name='agreement',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='claim',
            name='cheque_amt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='claim',
            name='cheque_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='claim',
            name='cheque_num',
            field=models.CharField(default=0.0, max_length=50),
        ),
        migrations.AddField(
            model_name='claim',
            name='cheque_pay_to',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='claim',
            name='claim_amt_agreed',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='claim',
            name='claim_approved_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='claim',
            name='claim_approvedby',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='claim',
            name='claim_approvedto',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='claim',
            name='claim_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='claim',
            name='claim_deductible',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='claim',
            name='claim_details',
            field=models.CharField(default='N/A', max_length=1000),
        ),
        migrations.AddField(
            model_name='claim',
            name='claim_estimate1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='claim',
            name='claim_estimate2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='claim',
            name='claim_estimate3',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='claim',
            name='claim_estimate4',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='claim',
            name='claim_estimate5',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='claim',
            name='claim_net_amt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='claim',
            name='claim_rejectedby',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='claim',
            name='claim_rejection_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='claim',
            name='claim_rejection_reason',
            field=models.CharField(default='N/A', max_length=1000),
        ),
        migrations.AddField(
            model_name='claim',
            name='claim_req_amt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='claim',
            name='coverage_type',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='claim',
            name='cust_fname',
            field=models.CharField(default='N/A', max_length=30),
        ),
        migrations.AddField(
            model_name='claim',
            name='cust_lname',
            field=models.CharField(default='N/A', max_length=30),
        ),
        migrations.AddField(
            model_name='claim',
            name='effective_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='claim',
            name='est_tier2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='claim',
            name='file_num',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='claim',
            name='goodwill',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='claim',
            name='po_num',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='claim',
            name='policy_type',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='claim',
            name='prob_description',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='claim',
            name='prob_part',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='claim',
            name='prob_side',
            field=models.CharField(choices=[('prob_bothsides', 'Both'), ('prob_leftside', 'Left'), ('prob_rightside', 'Right'), ('prob_noside', 'N/A')], default='N/A', max_length=30),
        ),
        migrations.AddField(
            model_name='claim',
            name='prob_type',
            field=models.CharField(choices=[('prob_fabric', 'Fabirc'), ('prob_leathvin', 'Leather/Vinyl'), ('prob_paint', 'Paint'), ('prob_rust', 'Rust'), ('prob_theft', 'Theft'), ('prob_undercoat', 'Undercoat')], default='Fabric', max_length=30),
        ),
        migrations.AddField(
            model_name='claim',
            name='process_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='claim',
            name='shop_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='claim',
            name='shop_address',
            field=models.CharField(default='1234 Main St', max_length=200),
        ),
        migrations.AddField(
            model_name='claim',
            name='shop_address2',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='claim',
            name='shop_contact',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='claim',
            name='shop_country',
            field=models.CharField(choices=[('CAN', 'Canada')], default='Canada', max_length=50),
        ),
        migrations.AddField(
            model_name='claim',
            name='shop_email',
            field=models.EmailField(blank=True, default='N/A', max_length=254),
        ),
        migrations.AddField(
            model_name='claim',
            name='shop_name',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='claim',
            name='shop_phone',
            field=models.CharField(default='123-456-7890', max_length=12),
        ),
        migrations.AddField(
            model_name='claim',
            name='shop_postalcode',
            field=models.CharField(default='A1A 1A1', max_length=7),
        ),
        migrations.AddField(
            model_name='claim',
            name='shop_province',
            field=models.CharField(choices=[('AB', 'Alberta'), ('BC', 'British Columbia'), ('MB', 'Manitoba'), ('NB', 'New Brunswick'), ('NL', 'Newfoundland and Labrador'), ('NT', 'Northwest Territories'), ('NS', 'Nova Scotia'), ('NU', 'Nunavut'), ('ON', 'Ontario'), ('PE', 'Prince Edward Island'), ('QC', 'Quebec'), ('SK', 'Saskatchewan'), ('YT', 'Yukon')], default='Ontario', max_length=50),
        ),
        migrations.AddField(
            model_name='claim',
            name='vin',
            field=models.CharField(default='JTHBP262495004947', max_length=30),
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('status_info', 'Information Only'), ('status_pending', 'Pending'), ('status_submitted', 'Submitted'), ('status_approved', 'Approved'), ('status_rejected', 'Rejected'), ('status_paid', 'Paid')], default='Information Only', max_length=50),
        ),
    ]
