# Generated by Django 4.1.7 on 2023-03-25 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0006_alter_claim_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('status_info', 'Information Only'), ('status_pending', 'Pending'), ('status_submitted', 'Submitted'), ('status_approved', 'Approved'), ('status_rejected', 'Rejected'), ('status_paid', 'Paid')], default='Information Only', max_length=50),
        ),
    ]
