# Generated by Django 4.1.7 on 2023-03-25 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0007_alter_claim_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='cheque_amt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='claim',
            name='cheque_num',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='claim',
            name='cheque_pay_to',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_amt_agreed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_approvedby',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_approvedto',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_deductible',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_details',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_estimate1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_estimate2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_estimate3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_estimate4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_estimate5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_net_amt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_rejectedby',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_rejection_reason',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_req_amt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='claim',
            name='shop_address2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='claim',
            name='shop_contact',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='claim',
            name='shop_country',
            field=models.CharField(choices=[('CAN', 'Canada')], default='CAN', max_length=50),
        ),
        migrations.AlterField(
            model_name='claim',
            name='shop_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
