# Generated by Django 4.1.7 on 2023-03-26 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0008_alter_claim_cheque_amt_alter_claim_cheque_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='cheque_amt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='cheque_date',
            field=models.DateTimeField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_amt_agreed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_approved_date',
            field=models.DateTimeField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_deductible',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_rejection_date',
            field=models.DateTimeField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_req_amt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='prob_description',
            field=models.TextField(default='N/A'),
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('prob_id', models.AutoField(primary_key=True, serialize=False)),
                ('prob_type', models.CharField(choices=[('prob_fabric', 'Fabirc'), ('prob_leathvin', 'Leather/Vinyl'), ('prob_paint', 'Paint'), ('prob_rust', 'Rust'), ('prob_theft', 'Theft'), ('prob_undercoat', 'Undercoat')], default='Fabric', max_length=30)),
                ('prob_description', models.TextField(default='N/A')),
                ('prob_part', models.CharField(default='N/A', max_length=50)),
                ('prob_side', models.CharField(choices=[('prob_bothsides', 'Both'), ('prob_leftside', 'Left'), ('prob_rightside', 'Right'), ('prob_noside', 'N/A')], default='N/A', max_length=30)),
                ('goodwill', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('claim_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='web_app.claim')),
            ],
        ),
    ]
