# Generated by Django 4.1.7 on 2023-03-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0012_alter_claim_claim_net_amt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='goodwill',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='prob_description',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='prob_part',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='prob_side',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='prob_type',
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_approved_date',
            field=models.DateTimeField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_estimate1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_estimate2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_estimate3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_estimate4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_estimate5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_net_amt',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_rejection_date',
            field=models.DateTimeField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='goodwill',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, null=True),
        ),
    ]
