# Generated by Django 4.1.7 on 2023-04-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0013_remove_claim_goodwill_remove_claim_prob_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_claims', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_dealership', models.CharField(max_length=100)),
                ('daily_sales', models.IntegerField()),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Work_order_form',
            fields=[
                ('work_order_form_number', models.AutoField(primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('product', models.CharField(default='Rust Protection', max_length=200)),
                ('quantity_used', models.CharField(default=1, max_length=200)),
                ('payment_amount', models.CharField(default=100, max_length=200)),
                ('customer_name', models.CharField(default='Bob', max_length=200)),
                ('customer_phone', models.CharField(default='7801234567', max_length=200)),
                ('vehicle_make', models.CharField(default='Honda', max_length=200)),
                ('vehicle_vin', models.CharField(default='11111', max_length=200)),
                ('dealership_name', models.CharField(default='Toyota', max_length=200)),
                ('dealership_phone', models.CharField(default='7801234567', max_length=200)),
                ('contact_name', models.CharField(default='Bob', max_length=200)),
                ('dealership_email', models.CharField(default='dealership@gmail.com', max_length=200)),
                ('address', models.CharField(default='47 Wallabeye Way', max_length=200)),
                ('country', models.CharField(default='Canada', max_length=200)),
                ('province', models.CharField(default='Alberta', max_length=200)),
                ('postal_code', models.CharField(default='T8V T9C', max_length=200)),
                ('text', models.CharField(max_length=200)),
            ],
        ),
    ]
